name: Tests

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php: [ '8.4','8.5' ]
                symfony: [ '6.4.*', '7.4.*', '8.*' ]

        name: PHPUnit (PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }})
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Cache Composer packages
                uses: actions/cache@v4
                with:
                    path: ~/.composer/cache
                    key: "php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-composer-${{ hashFiles('composer.json') }}-"
                    restore-keys: "php-"

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    tools: composer:v2,flex

            -   name: Install dependencies
                run: composer update --prefer-dist
                env:
                    SYMFONY_REQUIRE: "${{ matrix.symfony }}"

            -   name: Run PHPUnit
                run: vendor/bin/phpunit -c tools/phpunit.xml.dist --colors=always --no-coverage